### ISSUE TITLE
Would you be interested in adding Raincloud plots?

### ISSUE THREAD

**Issue by tungmilan** [erocoar/gghalves#3]
Do you think it's possible to make a `geom` for this type of [plot](https://github.com/RainCloudPlots/RainCloudPlots/blob/master/tutorial_R/raincloud_tutorial_r.pdf)? Thanks!

![](https://wellcomeopenresearch.s3.amazonaws.com/manuscripts/16574/5019bc28-6d22-4161-958e-49d66f5eef1f_Figure%20R6.gif)

![](https://wellcomeopenresearch.s3.amazonaws.com/manuscripts/16574/5019bc28-6d22-4161-958e-49d66f5eef1f_Figure%20R11.gif)

**Comment by Z3tt** [comment]
You can simply use what is already out there, e.g. https://github.com/RainCloudPlots/RainCloudPlots/blob/master/tutorial_R/raincloud_tutorial_r.Rmd or the functions provided in tjrtidybayes package (https://github.com/mjskay/tidybayes). I also think it doesn't fit the "half-geom" idea since it's a combination of several plot types and none of them is actually "halfed".
